In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Label Encoding

Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable.
The labels are usually assigned in alphabetical order or based on frequency.

For example, if we have categorical variable `color` with 3 possible values (red, green, blue) then we can represent it using label encoding as below:

1. Red: 1
2. Green: 2
3. Blue: 3

In [5]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red']
})

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
lbl_encoder = LabelEncoder()

In [8]:
lbl_encoder.fit_transform(df[['color']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2])

Here we can see, (Red: 2), (Green: 1), and (Blue: 0)

In [11]:
# We can get encoded value for data
lbl_encoder.transform([['red']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [13]:
# We can't get encoded value for unseen data during `fit`
# It will throw an error
# lbl_encoder.transform([['yellow']])

In [14]:
df['color'].shape

(5,)

In [15]:
df[['color']].shape

(5, 1)

# Ordinal Encoding

It is used to encode categorical data which has intrinsic order or ranking.

In this technique, each category is assigned a number based on its position in the order.

For example, if we have categorical variable `education_level` with 4 possible values (high school, college, graduate, post graduate) then we can represent it as below:

1. High School:  1
2. College: 2
3. Graduate: 3
4. Post Graduate: 4

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df2 = pd.DataFrame({
    'size': ['small','medium', 'large', 'medium', 'small', 'large']
})

In [19]:
ord_encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [20]:
ord_encoder.fit_transform(df2[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [21]:
ord_encoder.transform([['small']])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])